# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task10' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task10

  pod 'YandexMapsMobile', '4.1.0-lite'

end
